---

vagrant_box: ubuntu/trusty64

# If you need to run multiple instances of Drupal VM, set a unique hostname,
# machine name, and IP address for each instance.
vagrant_hostname: railsapp.local
vagrant_machine_name: railsapp
vagrant_ip: 192.168.100.100

# A list of synced folders, with the keys 'local_path', 'destination', 'id', and
# a 'type' of [nfs|rsync|smb] (leave empty for slow native shares). See
# http://docs.drupalvm.com/en/latest/extras/syncing-folders/ for more info.
vagrant_synced_folders:
  # The first synced folder will be used for the default Drupal installation, if
  # build_from_makefile is 'true'.
  - local_path: ~/ansible-railsbox
    destination: /var/www
    id: railsapp
    type: nfs
    create: true